name: Multistage_Pipeline_$(Date:yyyyMMdd) ($Rev:.r)
trigger: 
  - Main
stages:
- stage: BuildtheAPP
  jobs:
  - job: Build
    pool:
     name: Default
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'