name: Multistage_Pipeline
trigger: 
  - Main
stages:
- stage: BuildtheAPP
  jobs:
  - job: Build
    pool:
     vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
      name: 'NugetToolInstaller'
      displayName: 'Nuget Tool Installer'
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      name: 'Restore'
      displayName: 'Restore Code'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    
    - task: DotNetCoreCLI@2
      name: 'Build'
      displayName: 'Building Code'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
        
    - task: DotNetCoreCLI@2
      name: 'test'
      displayName: 'Testing Code'
      inputs:
        command: 'test'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
        testRunTitle: 'Unit Test'
        
    - task: DotNetCoreCLI@2
      name: 'Publish'
      displayName: 'Publish Code'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        
    
    - task: PublishBuildArtifacts@1
      name: 'PublishArtifact'
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'BuildArtifact'
        publishLocation: 'Container'
        
- stage: DeployApp
  jobs: 
  - job: Deploy
  pool:
   vmimage: 'Windows-latest'
   steps:
   - task: DownloadBuildArtifacts@1
     name: 'DownloadArtifact'
     displayName: 'Downloading Artifact'
     inputs:
       buildType: 'current'
       downloadType: 'specific'
       downloadPath: '$(System.ArtifactsDirectory)'

   - task: AzureRmWebAppDeployment@4
     name: 'DeployAPP'
     displayName: 'Deploying App'
     inputs:
       ConnectionType: 'AzureRM'
       azureSubscription: 'ARM Service Connection'
       appType: 'webApp'
       WebAppName: 'AppYamlAppservice'
       packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'