name: Multistage_Pipeline_$(Date:yyyyMMdd) ($Rev:.r)
trigger: 
  - Main
stages:
- stage: BuildtheAPP
  jobs:
  - job: Build
    pool:
     name: Default
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        
- stage: DeployApp
  jobs:
  - job: Deploy
    pool: 
      name: Default
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'ARM Service Connection'
        appType: 'webApp'
        WebAppName: 'AppYamlAppservice'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'


