name: Multistage_Pipeline_$(Date:yyyyMMdd) ($Rev:.r)
trigger: 
  - Main
stages:
- stage: BuildtheAPP
  jobs:
  - job: Build
    pool:
     vmImage: 'windows-latest'
    steps:
    - task: NuGetToolInstaller@1
      name: 'NugetToolInstaller'
      displayName: 'Nuget Tool Installer'
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'select'
        
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'