name: Multistage_Pipeline_$(Date:yyyyMMdd) ($Rev:.r)
trigger: 
  - Main
stages:
- stage: BuildtheAPP
  jobs:
  - job: Build
    pool:
     vmImage: 'windows-2019'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '''/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'''